name: Java CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Download and copy project to runner
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven #cache maven dependencies
      - name: Run tests
        run: mvn clean test -Dsuite=regression.xml
      - name: Generate report
        run: mvn allure::report
