name: Java CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven #cache maven dependencies
      - name: Run tests
        run: mvn clean test -Dsuite=regression.xml
      - name: Generate allure report
        run: mvn allure::report

      - name: Zip
        run: tar -cvf report.tar target
      - name: Get test tesults
        uses: actions/upload-artifact@v3
        with:
          name: allure report
          path: report.tar
