name: Java CI

on: workflow_dispatch

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
          cache: maven #cache maven dependencies
          
      - name: logs
        run: echo "$STAGE_CI_CONFIG"
      - name: Get valid properties
        run: echo $STAGE_CI_CONFIG >> $(pwd)/src/main/resources/config.properties && cat $(pwd)/src/main/resources/config.properties
        
      - name: Run tests
        run: mvn clean test -Dsuite=regression.xml -P stage
      
      - name: Generate allure report
        run: mvn allure::report

      - name: Zip
        run: tar -cvf report.tar target
        
      - name: Get test tesults
        uses: actions/upload-artifact@v3
        with:
          name: allure report
          path: report.tar
